/**
 * GatePass — Visitor Invitation Service (Feature 6 / Guest QR Ticket)
 *
 * Source: src/docs/specs/guest-qr-ticket.md
 * Source: Trustless-System-Auditor — default-deny on every failure path;
 *         the raw token leaves the server exactly ONCE (at issue).
 * Source: Security-and-Hardening — hash tokens before storage; never log
 *         or echo back the raw token after the issuing response.
 * Source: Code-Simplification — reuses the existing authorization_decisions
 *         table + qr-service.hashQrToken verbatim. No new schema, no new
 *         crypto primitive.
 *
 * Responsibilities:
 *   1. issueVisitorInvitation()    — admin/senior-guard. Mints a single-use
 *                                    QR token, stores its SHA-256 hash in
 *                                    authorization_decisions, emits an audit
 *                                    row, returns the raw token + pass URL.
 *   2. previewVisitorInvitation()  — public. Hashes the supplied token,
 *                                    looks up the invitation, returns
 *                                    only safe display fields. Does NOT
 *                                    mark the invitation as used.
 *
 * Hard rules:
 *   - Authorization is enforced UPSTREAM via requireAuth + requireRole.
 *     The service trusts that the caller has already passed that gate.
 *   - The raw token is generated by crypto.randomBytes(32). It is
 *     returned EXACTLY ONCE in the issue response. The audit row stores
 *     only the hash.
 *   - Default-deny on the preview path: not found, expired, and consumed
 *     each return a distinct ServiceError. The response shape never
 *     leaks "format invalid" vs "no match" — both map to 404.
 *   - The consume path is owned by qr-service.validateQrToken (already
 *     implemented, unchanged by F6). This service intentionally does NOT
 *     mark `is_used`.
 */

import { eq } from "drizzle-orm";
import { randomBytes, randomUUID } from "crypto";

import { authorizationDecisions } from "@/db/schema";
import { emitAuditEvent } from "./audit-logger";
import { ServiceError } from "./errors";
import { hashQrToken } from "./qr-service";
import { generatePin, generatePassRef, hashPin } from "./pin-service";
import {
  DEFAULT_TTL_HOURS,
  MAX_TTL_HOURS,
  VisitorInvitationErrorCodes,
  type IssueInvitationInput,
  type IssueInvitationResponse,
  type PreviewInvitationResponse,
} from "../validation/visitor-invitation-schemas";

// ─── DB shape ────────────────────────────────────────────────────────────────
// Loose typing so the service is mockable without a live Drizzle handle,
// matching the convention in visitor-profile-service.ts.

export interface DrizzleDB {
  select: (...args: unknown[]) => unknown;
  insert: (...args: unknown[]) => unknown;
  update: (...args: unknown[]) => unknown;
  transaction: (...args: unknown[]) => unknown;
  query: Record<string, unknown>;
  [key: string]: unknown;
}

// ─── Token primitives ────────────────────────────────────────────────────────

/**
 * Mints a 256-bit random token, base64url-encoded (RFC 4648 §5).
 *
 * Source: Security-and-Hardening — "Tokens must be cryptographically
 * random and have at least 128 bits of entropy". 32 bytes = 256 bits;
 * base64url avoids URL-unsafe chars so the token can be embedded in a
 * pass URL without further encoding.
 */
export function mintRawToken(): string {
  return randomBytes(32).toString("base64url");
}

/**
 * Public origin used to build the visitor's pass URL.
 *
 * Source: Security-and-Hardening — never let arbitrary user input
 * control outbound URLs. APP_PUBLIC_ORIGIN is operator-set in env.
 * Matches the existing pattern in approval-service.ts.
 */
function resolvePublicOrigin(): string {
  return process.env.APP_PUBLIC_ORIGIN ?? "http://localhost:5173";
}

/** Builds the visitor-facing pass URL from a raw token. */
export function buildPassUrl(rawToken: string): string {
  const origin = resolvePublicOrigin().replace(/\/+$/, ""); // strip trailing /
  return `${origin}/pass/${rawToken}`;
}

// ─── Row shape (subset of authorization_decisions we read back) ──────────────

interface AuthorizationRow {
  id: string;
  visitorName: string;
  host: string;
  unit: string;
  plate: string | null;
  expiresAt: Date;
  isUsed: boolean;
  usedAt: Date | null;
  pinLockedUntil: Date | null;
  createdAt: Date;
}

// ─── 1. Issue ────────────────────────────────────────────────────────────────

/**
 * Issues a single-use visitor invitation.
 *
 * Source: spec §6 "Issue".
 *
 * Order is critical:
 *   1. Mint raw token.
 *   2. Hash it (hash is what we store; raw never persists).
 *   3. INSERT authorization_decisions row.
 *   4. Emit audit event with the HASH (never the raw).
 *   5. Return the raw token + pass URL to the caller.
 *
 * The raw token leaves the server EXACTLY ONCE — in step 5. After this
 * response is sent, the only way to recover it is to re-issue. The
 * audit log + DB row contain only the hash.
 *
 * If step 3 fails, the audit emit is skipped (no orphan audit rows).
 * If step 4 fails (audit emit), the DB row remains but no entry can
 * ever be created against it without a guard scan — and the audit row
 * is emitted synchronously, so the only way step 4 fails is if the
 * audit-logger itself is broken, in which case the whole route fails.
 *
 * @param input  Already-Zod-validated request body.
 * @param actorId  Guard ID from the verified JWT (requireAuth).
 * @param db  Drizzle handle (request-scoped).
 * @throws ServiceError on internal failure (500 INTERNAL_ERROR).
 */
export async function issueVisitorInvitation(
  input: IssueInvitationInput,
  actorId: string,
  db: DrizzleDB,
): Promise<{ response: IssueInvitationResponse; statusCode: number }> {
  const traceId = `trace-${randomUUID()}`;

  // Step 1: mint raw token (256 bits of entropy).
  const rawToken = mintRawToken();

  // Step 2: hash it. We never store the raw token, anywhere.
  const qrTokenHash = hashQrToken(rawToken);

  // Step 3: compute expiry from TTL (with hard ceiling).
  // Source: spec §4 A5 — MAX_INVITATION_TTL_HOURS=168. The Zod schema
  // already rejects > MAX_TTL_HOURS at the boundary; this is a
  // belt-and-braces clamp in case the input ever bypasses Zod.
  const ttlHours = Math.min(input.ttlHours ?? DEFAULT_TTL_HOURS, MAX_TTL_HOURS);
  const issuedAt = new Date();
  const expiresAt = new Date(issuedAt.getTime() + ttlHours * 60 * 60 * 1000);

  // Step 3b: mint the One-Time PIN backup (Feature 11 / Stage 4).
  // The id is generated up front so the PIN hash can be salted with it in
  // the SAME insert (no post-insert update). The raw PIN leaves the server
  // only in the response; the DB stores just the HMAC. passRef is a
  // non-secret lookup key. PIN expiry == QR expiry (shared expiresAt).
  const decisionId = randomUUID();
  const rawPin = generatePin();
  const pinHash = hashPin(decisionId, rawPin);

  // Step 4: insert row. passRef is UNIQUE; on the (astronomically rare)
  // collision, regenerate the reference and retry a bounded number of times.
  let inserted: AuthorizationRow;
  let passRef = generatePassRef();
  const MAX_PASS_REF_RETRIES = 3;
  let attempt = 0;
  for (;;) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const rows = (await (db as any)
        .insert(authorizationDecisions)
        .values({
          id: decisionId,
          visitorName: input.visitorName,
          host: input.host,
          unit: input.unit,
          plate: input.plate ?? null,
          qrTokenHash,
          expiresAt,
          isUsed: false,
          passRef,
          pinHash,
          pinFailedAttempts: 0,
        })
        .returning()) as AuthorizationRow[];

      if (!rows || rows.length === 0) {
        throw new Error("INSERT returned no rows");
      }
      inserted = rows[0];
      break;
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      const isPassRefCollision = /pass_ref/i.test(message);
      if (isPassRefCollision && attempt < MAX_PASS_REF_RETRIES) {
        attempt += 1;
        passRef = generatePassRef();
        continue;
      }
      // Failure → no audit row, no response. Caller surfaces 500.
      throw new ServiceError(
        VisitorInvitationErrorCodes.INTERNAL_ERROR,
        isPassRefCollision ? "Failed to allocate a unique pass reference" : message,
        500,
      );
    }
  }

  // Step 5: emit audit (synchronous; raw token NEVER in payload).
  await emitAuditEvent("qr_invitation_issued", actorId, traceId, {
    invitationId: inserted.id,
    qrTokenHash,
    expiresAt: expiresAt.toISOString(),
    ttlHours,
    visitorName: input.visitorName,
    host: input.host,
    unit: input.unit,
  });

  // Step 6: build response with the RAW token (exits the server once).
  const response: IssueInvitationResponse = {
    invitation: {
      id: inserted.id,
      qrToken: rawToken,
      passUrl: buildPassUrl(rawToken),
      passRef,
      pin: rawPin,
      visitorName: inserted.visitorName,
      host: inserted.host,
      unit: inserted.unit,
      plate: inserted.plate,
      expiresAt: inserted.expiresAt.toISOString(),
      issuedAt: inserted.createdAt.toISOString(),
    },
    traceId,
  };

  return { response, statusCode: 201 };
}

// ─── 2. Preview ──────────────────────────────────────────────────────────────

/**
 * Previews an invitation for the visitor's pass page.
 *
 * Source: spec §6 "Preview".
 *
 * Order:
 *   1. Hash the supplied token (treat as untrusted).
 *   2. SELECT authorization_decisions by hash.
 *   3. NOT FOUND → 404 INVITATION_NOT_FOUND.
 *   4. EXPIRED  → 410 INVITATION_EXPIRED.
 *   5. CONSUMED → 410 INVITATION_CONSUMED.
 *   6. LOCKED   → 423 INVITATION_LOCKED (Feature 11 PIN limiter).
 *   7. Otherwise → 200 with safe display fields ONLY.
 *
 * This path NEVER writes. It NEVER marks is_used. It NEVER emits an
 * audit row (reads don't emit; the consume path emits qr_scan_*).
 *
 * @throws ServiceError on every non-200 branch (route maps to status).
 */
export async function previewVisitorInvitation(
  rawToken: string,
  db: DrizzleDB,
): Promise<{ response: PreviewInvitationResponse; statusCode: number }> {
  // Step 1: hash. The route already validated token shape via Zod, but
  // the hash is computed even for a borderline-malformed token so the
  // response shape does not leak "format invalid" vs "no match".
  const qrTokenHash = hashQrToken(rawToken);

  // Step 2: lookup.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const rows = (await (db as any)
    .select()
    .from(authorizationDecisions)
    .where(eq(authorizationDecisions.qrTokenHash, qrTokenHash))
    .limit(1)) as AuthorizationRow[];

  if (!rows || rows.length === 0) {
    throw new ServiceError(
      VisitorInvitationErrorCodes.INVITATION_NOT_FOUND,
      "No invitation matches this pass link",
      404,
      "token",
    );
  }

  const row = rows[0];

  // Step 3: expired? expires_at is stored UTC; new Date() is UTC.
  if (row.expiresAt.getTime() <= Date.now()) {
    throw new ServiceError(
      VisitorInvitationErrorCodes.INVITATION_EXPIRED,
      "This pass has expired",
      410,
      "token",
    );
  }

  // Step 4: consumed?
  if (row.isUsed) {
    throw new ServiceError(
      VisitorInvitationErrorCodes.INVITATION_CONSUMED,
      "This pass has already been used",
      410,
      "token",
    );
  }

  // Step 5: locked by the PIN limiter? The pass will be refused at the gate,
  // so the visitor must not be shown a "valid until …" pass. Told, not
  // surprised at the barrier.
  if (row.pinLockedUntil && row.pinLockedUntil.getTime() > Date.now()) {
    throw new ServiceError(
      VisitorInvitationErrorCodes.INVITATION_LOCKED,
      "This pass is locked after too many incorrect PIN attempts",
      423,
      "token",
    );
  }

  // Step 6: success — safe display fields ONLY.
  // We deliberately omit the row id, hash, used_*, created_at — the
  // visitor's phone has no need for them and we don't want them in
  // the pass page's HTML source.
  const response: PreviewInvitationResponse = {
    invitation: {
      visitorName: row.visitorName,
      host: row.host,
      unit: row.unit,
      plate: row.plate,
      expiresAt: row.expiresAt.toISOString(),
    },
  };

  return { response, statusCode: 200 };
}
